# Generated by Django 2.0.3 on 2018-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='module_id',
            field=models.IntegerField(unique=True),
        ),
    ]
